<?php


$articlesSunny = array(
	array('title' => 'Heat wave '.ucfirst($city).' - Wikipedia', 'url' => 'https://en.wikipedia.org/wiki/Heat_wave', 'description' => 'A heat wave is a prolonged period of excessively hot weather, which may be accompanied by ... Severe heat waves have caused catastrophic crop failures, thousands of deaths from hyperthermia, and widespread power outages due to ...'),
	array('title' => 'National and Local Weather Forecast, Hurricane, Radar and Report', 'url' => 'https://weather.com/', 'description' => 'The Weather Channel and weather.com provide a national and local weather forecast for cities, as well as weather radar, report and hurricane coverage.'),
	array('title' => 'Extreme weather - Climate Emergency Institute', 'url' => 'www.climateemergencyinstitute.com/extreme_weather.html', 'description' => 'The rapid increase ​​is '.ucfirst($city).' extreme weather threatens global catastrophe because all the world\'s best food producing regions are in the ...'),
	array('title' => 'Weather forecast: '.ucfirst($city).' heatwave hell', 'url' => 'www.news.com.au/.../weather.../2987928bc491cd60b3c5543ba36.', 'description' => ' In fact, it\'s so hot you should just stay indoors or by the pool for record weather that is set to strain hospitals, bring \'catastrophic\' fire threats to ...'),
	array('title' => ''.ucfirst($city).' faces catastrophic fire danger as temperatures reach reach ...', 'url' => 'www.independent.co.uk › News › World › '.ucfirst($city).'', 'description' => ''.ucfirst($city).' faces catastrophic fire danger as temperatures reach reach record levels in heatwave. This is not a usual fire day, this is as bad as it ...'),
	array('title' => 'Heatwave '.ucfirst($city).': catastrophic fire danger looms, residents told to leave', 'url' => 'www.theaustralian.com.au/.../heatwave-catastrophic.../b6b2205ee3...', 'description' => 'Dozens of properties could be damaged or destroyed and at least one person has treated for burns as almost 100 fires burn across '.ucfirst($city).'.'),
	array('title' => ''.ucfirst($city).' braces for catastrophic record-breaking heatwave | Stuff.co.nz', 'url' => 'www.stuff.co.nz/.../'.ucfirst($city).'-braces-for-catastrophic-recordbreaking...', 'description' => ''.ucfirst($city).' is bracing for a "catastrophic" record heatwave that is set to swelter all weekend.')
	);
$articlesCold = array(
	array('title' => 'Extreme Cold Weather Alert - City of '.ucfirst($city).'', 'url' => 'www1.'.ucfirst($city).'.ca/wps/portal/contentonly?vgnextoid...', 'description' => 'This page contains information on extreme cold weather and alerts.'),
	array('title' => 'Winter storm '.ucfirst($city).' - Wikipedia', 'url' => 'https://en.wikipedia.org/wiki/Winter_storm', 'description' => 'A winter storm is an event in which varieties of precipitation are formed that only occur at low temperatures, such as snow or sleet, or a rainstorm where ground ...'),
	array('title' => 'Snowstorms & Extreme Cold | Ready.gov', 'url' => 'https://www.ready.gov/winter-weather', 'description' => 'This page explains what actions to take when you receive a winter weather storm alert from the National Weather Service for your local area and what to do ...'),
	array('title' => 'Winter is coming — and its bringing a \'catastrophe ... - Business Insider', 'url' => 'www.businessinsider.com/ap-eu-warns-of-refugee-catastrophe-as-...', 'description' => 'The European Union warned on Monday of a humanitarian "catastrophe" with thousands of people traveling to '.ucfirst($city).' as winter ...'),
	array('title' => ''.ucfirst($city).' Is Being Clobbered With Snow Already, and That Could Mean ...', 'url' => 'https://weather.com/.../weather/.../snow-'.ucfirst($city).'-russia-united-states-...', 'description' => 'Early in the calendar year, the air coming from '.ucfirst($city).' can be cold ... This is a home run for weather systems and allows cold air to get into the ....'),
	array('title' => 'Extreme cold weather alert issued for '.ucfirst($city).' - '.ucfirst($city).' - CBC News', 'url' => 'www.cbc.ca/news/canada/.../extreme-cold-weather-alert-1.3963145', 'description' => 'The city\'s acting medical officer of health has issued an extreme cold weather alert for '.ucfirst($city).' as temperatures dip well below freezing.'),
	array('title' => 'SNOW weather forecast updates: '.ucfirst($city).' set for killer cold weather in ...', 'url' => 'www.express.co.uk › News › Weather', 'description' => ''.ucfirst($city).' is on big freeze alert prompting health officials to ramp up warnings to take care in killer cold weather.')
);
?>